name: 'Next Version'
description: 'Determine next release version for given major version, using existing tags'
branding:
  color: blue
  icon: trending-up
inputs:
  base:
    description: 'Base version, e.g. "v1", "2.3" or "refs/heads/releases/v1"'
    default: ${{ github.ref }}
    required: false
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
outputs:
  base:
    description: 'Normalized base version'
  last:
    description: 'Last existing version found for given base'
  next:
    description: 'Next release version'
runs:
  using: 'node12'
  main: 'dist/index.js'
