name: 'Next Version'
description: 'Determine next release version for given major version, using existing tags'
inputs:
  base:
    description: 'Base version, e.g. "v1", "2.3" or "refs/heads/releases/v1"'
    required: true
outputs:
  base:
    description: 'Normalized base version'
  last:
    description: 'Last existing version found for given base'
  next:
    description: 'Next release version'
runs:
  using: 'node12'
  main: 'dist/index.js'
