name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        id: version
        with:
          base: "refs/heads/releases/x1"
      - run: |
          if [[ "${{steps.version.outputs.base}}" != "x1" ]]; then
            exit 1
          fi
          if [[ "${{steps.version.outputs.next}}" != "x1.0" ]]; then
            exit 1
          fi
